import numpy as np
import plotly.graph_objects as go

###################################################################################################################
# STRATEGY QUALITY MEASURES UTILS
###################################################################################################################


def rtp(pnl, best_pnl, worst_pnl, one_sided):
    """
    Compute the Relative Trading Performance (RTP).

    Parameters
    ----------
    pnl : array-like
        Realized PnL values.
    best_pnl : array-like
        Best-case PnL trajectory.
    worst_pnl : array-like
        Worst-case PnL trajectory.
    one_sided : bool
        If True, scales RTP between worst and best PnL.
        If False, scales PnL by the best PnL only.

    Returns
    -------
    float
        Relative trading performance.
    """
    if one_sided:
        return (np.sum(pnl) - np.sum(worst_pnl)) / (
            np.sum(best_pnl) - np.sum(worst_pnl)
        )
    else:
        return np.sum(pnl) / np.sum(best_pnl)


def hhi(pnl):
    """
    Compute the Herfindahl–Hirschman Index (HHI) of profit concentration.

    Parameters
    ----------
    pnl : array-like
        Profit or PnL series.

    Returns
    -------
    float
        HHI concentration measure (0 to 1).
    """
    return np.sum((pnl / np.sum(pnl)) ** 2)


def gini(pnl):
    """
    Compute the Gini coefficient of profit concentration using pairwise differences.

    Parameters
    ----------
    pnl : array-like
        Profit or return series.

    Returns
    -------
    float
        Gini coefficient, between 0 and 1.
    """
    pnl = pnl[pnl > 0]  # only positive profits
    n = pnl.size
    if n == 0:
        return 0.0
    mean_x = np.mean(pnl)
    if mean_x == 0:
        return 0.0
    diff_sum = np.abs(pnl[:, None] - pnl).sum()  # pairwise absolute differences
    return diff_sum / (2 * n**2 * mean_x)


def topk_contribution(pnl, k=2016):
    """
    Compute the percentage contribution of the top-k profitable points.

    Parameters
    ----------
    pnl : array-like
        Profit or PnL series.
    k : int, optional
        Number of top profit observations to consider.
        Default 2016 corresponds to 21 days * 96 quarter hours of paid leave common in EU.

    Returns
    -------
    float
        Fraction of total profit generated by the top-k positive PnL values.
    """
    positives = pnl[pnl > 0]
    if positives.size == 0:
        return 0.0
    total_profit = positives.sum()
    topk_sum = np.sort(positives)[-k:].sum() if positives.size >= k else positives.sum()

    return topk_sum / total_profit


def profit(pnl):
    """
    Compute total profit.
    """
    return np.sum(pnl)


def mdd(pnl):
    """
    Compute the maximum drawdown.
    """
    equity = np.cumsum(pnl)
    peak = np.maximum.accumulate(equity)
    drawdown = peak - equity
    return np.max(drawdown)


def avg_dd(pnl):
    """
    Compute average drawdown.
    """
    equity = np.cumsum(pnl)
    peak = np.maximum.accumulate(equity)
    drawdown = peak - equity
    return np.mean(drawdown)


def downside_std(pnl, one_sided):
    """
    Compute downside standard deviation.
    """
    if one_sided:
        mu = np.mean(pnl)
        diff = pnl - mu
        downside_sq = np.where(diff < 0, diff**2, 0.0)
    else:
        downside_sq = np.where(pnl < 0, pnl**2, 0.0)

    return np.sqrt(downside_sq.mean())


def win_rate(pnl):
    """
    Compute win rate (fraction of positive-PnL observations).
    """
    return len(pnl[pnl > 0]) / len(pnl)


###################################################################################################################
# BANDS UTILS
###################################################################################################################


def calc_band(M, Y, idx, band_type):
    """
    Compute an upper or lower prediction band for a given index.

    Parameters
    ----------
    M : array-like
        Summary statistic per path (max or min).
    Y : ndarray
        Forecast ensemble of shape (T, Npaths).
    idx : int
        Index corresponding to quantile level.
    band_type : {'upper', 'lower'}
        Band type selection.

    Returns
    -------
    ndarray
        Band values for each time step.
    """
    if band_type == "upper":
        lt = np.argsort(M)[: idx + 1]
        B = np.max(Y[:, lt], axis=1)
    elif band_type == "lower":
        lt = np.argsort(M)[::-1][: idx + 1]
        B = np.min(Y[:, lt], axis=1)
    return B


def vanilla_band(Y, scp, band_type):
    """
    Compute a vanilla (unweighted) prediction band.

    Parameters
    ----------
    Y : ndarray
        Forecast ensemble (T x Npaths).
    scp : float
        Probability level of the band.
    band_type : {'upper', 'lower'}
        Which band to compute.

    Returns
    -------
    ndarray
        Prediction band across time.
    """
    m = np.shape(Y)[1]
    if band_type == "upper":
        M = np.max(Y, axis=0)
    elif band_type == "lower":
        M = np.min(Y, axis=0)

    if scp >= 0.5:
        levels = np.arange(1, m + 1) / m
    elif scp < 0.5:
        levels = np.arange(0, m) / m

    idx = min([np.searchsorted(levels, scp), len(levels) - 1])
    if levels[idx] == scp or idx == 0:
        B = calc_band(M, Y, idx, band_type=band_type)
    else:
        B1 = calc_band(M, Y, idx - 1, band_type=band_type)
        B2 = calc_band(M, Y, idx, band_type=band_type)
        l1, l2 = levels[idx - 1], levels[idx]
        denominator = l2 - l1
        nominator_1 = B1 * (l2 - scp)
        nominator_2 = B2 * (scp - l1)
        B = (nominator_1 + nominator_2) / denominator
    return B


def calc_weighted_band(Y, idx, band_type):
    """
    Compute a weighted band given pre-sorted paths.

    Parameters
    ----------
    Y : ndarray
        Forecast ensemble.
    idx : int
        Index corresponding to weight level.
    band_type : {'upper','lower'}

    Returns
    -------
    ndarray
        Weighted prediction band.
    """
    if band_type == "upper":
        B = np.max(Y[:, : idx + 1], axis=1)
    elif band_type == "lower":
        B = np.min(Y[:, : idx + 1], axis=1)
    return B


def sort_values_and_weights(weights, values, Y, band_type):
    """
    Sort values, weights, and ensemble paths for weighted band calculation.

    Parameters
    ----------
    weights : array-like
        Path weights.
    values : array-like
        Max/min summary stats per path.
    Y : ndarray
        Forecast ensemble (T x Npaths).
    band_type : {'upper','lower'}

    Returns
    -------
    levels : ndarray
        Cumulative weight levels.
    values_sorted : ndarray
        Sorted values.
    Y_sorted : ndarray
        Forecast ensemble sorted by values.
    """
    if band_type == "upper":
        i = np.argsort(values)
    elif band_type == "lower":
        i = np.argsort(values)[::-1]
    values_sorted = values[i]
    w_sorted = weights[i]
    Y_sorted = Y[:, i]
    levels = np.cumsum(w_sorted)
    return levels, values_sorted, Y_sorted


def weighted_band(Y, weights, scp, band_type):
    """
    Compute a weighted prediction band.

    Parameters
    ----------
    Y : ndarray
        Forecast ensemble (T x Npaths).
    weights : array-like
        Path weights summing to 1.
    scp : float
        Coverage probability.
    band_type : {'upper','lower'}

    Returns
    -------
    ndarray
        Weighted prediction band.
    """
    if band_type == "upper":
        M = np.max(Y, axis=0)
    elif band_type == "lower":
        M = np.min(Y, axis=0)
    levels, M_sorted, Y_sorted = sort_values_and_weights(
        weights, M, Y, band_type=band_type
    )

    idx = min([np.searchsorted(levels, scp), len(levels) - 1])

    if levels[idx] == scp or idx == 0:
        B = calc_weighted_band(Y_sorted, idx, band_type=band_type)
    else:
        B1 = calc_weighted_band(Y_sorted, idx - 1, band_type=band_type)
        B2 = calc_weighted_band(Y_sorted, idx, band_type=band_type)

        l1, l2 = levels[idx - 1], levels[idx]
        denominator = l2 - l1
        nominator_1 = B1 * (l2 - scp)
        nominator_2 = B2 * (scp - l1)
        if denominator == 0:  # edge case that should not happen
            raise ValueError("Denominator for weighted path is 0")
        B = (nominator_1 + nominator_2) / denominator

    return B


###################################################################################################################
# WEIGHTS UTILS
###################################################################################################################


def weighted_median(values, weights):
    """
    Compute the weighted median of a set of values.

    Parameters
    ----------
    values : array-like
        Data values.
    weights : array-like
        Corresponding weights.

    Returns
    -------
    float
        Weighted median (linear interpolation if needed).
    """
    i = np.argsort(values)
    v, w = values[i], weights[i]
    c = np.cumsum(w)
    p = 0.5
    idx = min([np.searchsorted(c, p), len(c) - 1])

    if c[idx] == p or idx == 0:
        return v[idx]
    else:
        c1, c2 = c[idx - 1], c[idx]
        v1, v2 = v[idx - 1], v[idx]
        denominator = c2 - c1
        nominator_1 = v1 * (c2 - p)
        nominator_2 = v2 * (p - c1)
        interpolated_value = (nominator_1 + nominator_2) / denominator
        return interpolated_value


def compute_weights(
    forecast_so_far, observed_so_far, kernel_width, p, lambda_, weights_method="kernel"
):
    """
    Compute normalized path weights given forecasts and observations.

    Parameters
    ----------
    forecast_so_far : ndarray
        Shape (t+1, Npaths). Forecast history for each path.
    observed_so_far : ndarray
        Shape (t+1,). Observed historical values.
    kernel_width : float
        Kernel width parameter.
    p : float
        Norm degree (p=2 → Gaussian kernel).
    lambda_ : float
        Time-decay factor for weighting past errors.
    weights_method : {'kernel','mae'}
        Weighting scheme selection.

    Returns
    -------
    ndarray
        Normalized weights of shape (Npaths,).
    """
    # compute errors per path
    diffs = forecast_so_far - observed_so_far[:, None]

    times = np.arange(len(observed_so_far))
    age = len(observed_so_far) - 1 - times
    w_time = np.exp(-lambda_ * age)
    w_time /= np.sum(w_time)

    if weights_method == "kernel":
        # we are calculating the kernel on TIME DIMENSION vectors: so each observation from trajectory is a vector element, we apply decay weight and sum over it
        err = np.sum(w_time[:, None] * (np.abs(diffs)) ** 2, axis=0)
        raw = np.exp(
            -kernel_width * (err ** (p / 2))
        )  # for p = 2 it is gaussian kernel

        # scale the weights so that they sum to 1
        s = np.sum(raw)
        if (
            s == 0 or not np.isfinite(s)
        ):  # it can happen that the error is large and we are not able to scale efficiently with any of our paths
            N = raw.size
            return np.ones(N) / N

        weights = raw / s
    elif weights_method == "mae":
        diffs = np.where(
            diffs == 0, 1e-6, diffs
        )  # handle the rare cases (~30) where naive sampling gave us exact price (can happen sometimes especially in night hours)
        all_paths_mae = np.mean(np.abs(diffs), axis=0)
        inverse_mae = 1 / all_paths_mae
        weights = inverse_mae / np.sum(inverse_mae)

    return weights


###################################################################################################################
# DEVEL TRAJECTORIES PLOTS UTILS
###################################################################################################################


def add_curve(fig, x, y, name, color):
    """
    Add a curve trace to a Plotly figure.
    """
    fig.add_trace(
        go.Scatter(x=x, y=y, mode="lines+markers", name=name, line=dict(color=color))
    )


###################################################################################################################
# NOVEL PROBABILISTIC FORECAST MEASURES UTILS
###################################################################################################################


def weighted_classification_accuracy(y_actual, y_forecast, naive):
    """
    Compute Weighted Classification Accuracy (WCA) and vanilla CA.

    Parameters
    ----------
    y_actual : array-like
        Observed realizations.
    y_forecast : ndarray
        Forecast ensemble (T x Npaths).
    naive : array-like
        Naive benchmark.

    Returns
    -------
    wca : float
        Weighted classification accuracy.
    vanilla_ca : float
        Unweighted classification accuracy.
    """

    y_forecast_median = np.median(y_forecast, axis=1)
    indic_fore = np.where(
        y_forecast_median > naive, 1, np.where(y_forecast_median < naive, -1, 0)
    )
    indic_actual = np.where(y_actual > naive, 1, np.where(y_actual < naive, -1, 0))

    # Compute weights: Higher MAE means higher penalty
    mae = np.abs(y_actual - y_forecast_median)
    weights = 1 + (
        (mae - np.min(mae)) / (np.max(mae) - np.min(mae))
    )  # Normalize by mean MAE

    # Compute weighted misclassification
    misclassified = (indic_actual != indic_fore).astype(int)
    weighted_misclassification = np.sum(weights * misclassified)

    # Compute WCA
    wca = 1 - (weighted_misclassification / np.sum(weights))

    # Compute vanilla (unweighted) CA
    vanilla_ca = 1 - np.sum(misclassified) / len(misclassified)

    return wca, vanilla_ca


def probabilistic_weighted_classification_accuracy(y_actual, y_forecast, naive):
    """
    Compute the Probabilistic Weighted Classification Accuracy (PWCA)
    and vanilla CA.

    Parameters
    ----------
    y_actual : array-like
        Observed values.
    y_forecast : ndarray
        Forecast ensemble.
    naive : array-like
        Naive benchmark.

    Returns
    -------
    wca : float
        Probabilistic weighted classification accuracy.
    vanilla_ca : float
        Unweighted classification accuracy.
    """

    y_forecast_median = np.median(y_forecast, axis=1)
    indic_fore = np.where(
        y_forecast_median > naive, 1, np.where(y_forecast_median < naive, -1, 0)
    )
    indic_actual = np.where(y_actual > naive, 1, np.where(y_actual < naive, -1, 0))

    # Compute weights: Higher MAE means higher penalty
    mae = np.abs(y_actual - y_forecast_median)
    weights = 1 + (
        (mae - np.min(mae)) / (np.max(mae) - np.min(mae))
    )  # Normalize by mean MAE

    # Correct weights by the probability
    y_na = naive.reshape(-1, 1)
    y_fc = y_forecast
    below = (y_fc < y_na).mean(axis=1)
    equal = (y_fc == y_na).mean(axis=1)
    above = (y_fc > y_na).mean(axis=1)
    probab = np.where(indic_fore == -1, below, np.where(indic_fore == 0, equal, above))

    # Compute weighted misclassification
    misclassified = (indic_actual != indic_fore).astype(int)
    weighted_misclassification = np.sum(weights * probab * misclassified)

    # Compute WCA
    wca = 1 - (weighted_misclassification / np.sum(weights * probab))

    # Compute vanilla (unweighted) CA
    vanilla_ca = 1 - np.sum(misclassified) / len(misclassified)

    return wca, vanilla_ca


###################################################################################################################
# STRATEGY UTILS
###################################################################################################################


def get_trust_threshold(residuals, trust_threshold_method):
    """Comppute the trust threshold for trading decision change in dynamic strategies."""
    raw_median_mae = np.mean(np.abs(residuals))

    if len(residuals) > 1:
        sigma = np.std(residuals)
        iqr = np.subtract(*np.percentile(residuals, [75, 25]))
        ipr = np.subtract(*np.percentile(residuals, [95, 5]))
    else:
        sigma = np.sqrt(np.sum((residuals) ** 2))
        iqr = np.mean(np.abs(residuals))
        ipr = np.mean(np.abs(residuals))

    if trust_threshold_method == "3sigma":
        trust_threshold = 3 * sigma
    elif trust_threshold_method == "iqr":
        trust_threshold = iqr
    elif trust_threshold_method == "5_95_IPR":
        trust_threshold = ipr
    elif trust_threshold_method == "mae":
        trust_threshold = raw_median_mae

    nonzero_mae = max([raw_median_mae, 0.01])

    return trust_threshold, nonzero_mae
